apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: {{ .Release.Name }}-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secrets.secretManagerKey }}
