packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true

catalog:
  "@types/node": "^24"
  typescript: "^6"

injectWorkspacePackages: true
